name: Auto-Format with Black

# 1) Schreibzugriff für push() zulassen
permissions:
  contents: write

on:
  push:
    branches: [ main, develop ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  black:
    runs-on: ubuntu-latest
    # verhindert Endlosschleife durch eigene Commits
    if: ${{ github.actor != 'github-actions[bot]' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Token mit Schreibrechten wird automatisch per `permissions` freigegeben
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Black
        run: pip install black

      - name: Run Black formatter
        run: black .

      - name: Commit & push formatted code
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "style: apply automatic Black formatting"
          file_pattern: "**/*.py"
          # korrekte Inputs für Git-Nutzer
          commit_user_name: github-actions
          commit_user_email: github-actions@users.noreply.github.com

