name: Build & publish service images to GHCR
on:
  push: { branches: [ '**' ] }
permissions: { contents: read, packages: write }

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ consumer, emitter, model_service ]
      fail-fast: false

    env:
      REGISTRY: ghcr.io

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    #   produce a lowercase repo path once and expose it as an output
    - name: Canonical image namespace
      id: vars
      run: |
        echo "image_base=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >>"$GITHUB_OUTPUT"

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username:  ${{ github.actor }}
        password:  ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Buildx
      uses: docker/setup-buildx-action@v3

    #  use that output everywhere you need the repo name
    - name: Build & push ${{ matrix.service }}
      uses: docker/build-push-action@v5
      with:
        context: ./icecube-pipeline/${{ matrix.service }}
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ steps.vars.outputs.image_base }}/${{ matrix.service }}:${{ github.sha }}
          ${{ env.REGISTRY }}/${{ steps.vars.outputs.image_base }}/${{ matrix.service }}:latest
        labels: |
          org.opencontainers.image.source=${{ github.repositoryUrl }}
          org.opencontainers.image.revision=${{ github.sha }}
        provenance: false

