name: Update per-container requirements.txt

on:
  push:
    branches:
      - main
    paths:
      - '**/*.py'        # run only when Python files change
  pull_request:
    paths:
      - '**/*.py'        # same for PRs

permissions:
  contents: write
  pull-requests: write

jobs:
  pigar-update:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pigar
        run: pip install --quiet --upgrade pigar

      - name: Run pigar in each container
        run: .github/scripts/update_requirements.sh

      - name: Commit & push back (if anything changed)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update per-container requirements.txt with pigar"
          commit_author: GitHub Action <actions@github.com>
          push_options: '--follow-tags'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

